version: '3.8'

services:
  app:
    build:
      context: .
    container_name: wgca-container
    volumes:
      - /home/holycan/go/src/wgca:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["air", "-c", "air-linux.toml"]
